version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: yellow_user
      POSTGRES_PASSWORD: yellow_pass
      POSTGRES_DB: yellow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://yellow_user:yellow_pass@db:5432/yellow
    depends_on:
      - db
    command: npm start

volumes:
  pgdata:

